### ISSUE TITLE
When running que.setup: (Memento.MnesiaException) Mnesia operation failed

### ISSUE THREAD

**Issue by krainboltgreene** [sheharyarn/que#23]
```
𝑓 1 mix que.setup
** (Memento.MnesiaException) Mnesia operation failed
   {'Bad type on some provided arguments', Que.Persistence.Mnesia.DB.Jobs, :disc_copies, :nonode@nohost}
   Mnesia Error: {:bad_type, Que.Persistence.Mnesia.DB.Jobs, :disc_copies, :nonode@nohost}
    lib/memento/table/table.ex:274: Memento.Table.handle_for_bang!/1
    (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.3) lib/mix/cli.ex:82: Mix.CLI.run_task/2
    (elixir 1.10.3) lib/code.ex:926: Code.require_file/2
```

Not really sure where this could be happening.

**Comment by krainboltgreene** [comment]
TIL: `# Notice the single quotes`

I didn't know single quotes worked this way in elixir.
